name:       blog
version:    0.1.0.0
category:   Web
author:     Tosainu
maintainer: tosainu.maple@gmail.com
copyright:  Copyright (c) 2018 Tosainu
license:    MIT
github:     Tosainu/blog

extra-source-files:
  - README.md

dependencies:
  - aeson
  - base
  - blaze-html
  - blaze-markup
  - bytestring
  - containers
  - filepath
  - hakyll
  - hakyll-sass
  - lucid
  - mtl
  - pandoc
  - process
  - skylighting
  - tagsoup
  - text
  - time
  - transformers
  - uri-encode
  - unordered-containers
  - vector

executables:
  blog:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -threaded -Wall
